<?xml version="1.0" encoding="utf-8"?><Database Name="CryptoDB" Class="CryptoLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-SHIJ6MT\CRYPTO;Initial Catalog=CryptoDB;Persist Security Info=True;User ID=sa" SettingsObjectName="Proiect.NET.Properties.Settings" SettingsPropertyName="CryptoDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>